name: Build image and push to Registry (Github Runner)

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "Image tag"
        default: 'NaN'
    secrets:
      REGISTRY_PATH:
        required: true
      REGISTRY_LOGIN:
        required: true
      REGISTRY_PASSWORD:
        required: true
      IMAGE_NAME:
        required: true
        

jobs:
  build:
    name: Build and Deploy
    if: github.event.inputs.version != 'NaN'
    runs-on: ubuntu-latest
    env:
      SEMVER: ${{ github.event.inputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1 
      with:
        registry: https://${{ secrets.REGISTRY_PATH }}
        username: ${{ secrets.REGISTRY_LOGIN }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
  
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_PATH }}/${{ secrets.IMAGE_NAME }}:$SEMVER
        # cache-from: type=registry,ref=user/app:buildcache
        # cache-to: type=registry,ref=user/app:buildcache,mode=max