name: Update host service (Self-hosted)

on: 
  workflow_call:
    inputs:
      version:
        required: true
        default: 'NaN'
        type: string
    secrets:
      Registry_Path:
        required: true
      Registry_Login:
        required: true
      Registry_Password:
        required: true
      Image_Name:
        required: true
      Swarm_Service_Name:
        required: true

jobs:
  deploy:
    name: Update Docker image in Swarm
    if: inputs.version != 'NaN'
    runs-on: self-hosted
    env:
      IS_CONTAINS: 'false'
      IMAGE_VERSION: ${{ inputs.version }}
      SERVICE_NAME: ${{ inputs.service_name }}
    steps:
      - name: Validate image in registry
        if: env.IMAGE_VERSION != 'NaN'
        shell: bash
        run: |
          REP_INFO=$(curl -u ${{ secrets.Registry_Login }}:${{ secrets.Registry_Password }} https://${{ secrets.Registry_Path }}/v2/${{ secrets.Image_Name }}/tags/list)
          if [[ "$REP_INFO" == *"$IMAGE_VERSION"* ]]; then
            echo "IS_CONTAINS=true" >> $GITHUB_ENV
          fi
      - name: Update Swarm service
        if: env.IS_CONTAINS == 'true'
        run: sudo docker service update ${{ secrets.Swarm_Service_Name }} --with-registry-auth --image ${{ secrets.Registry_Path }}/${{ secrets.Image_Name }}:$IMAGE_VERSION